// SPDX-License-Identifier: MIT
// GENERATED by tools/genvec.mjs -- real P-256 signatures, do not edit by hand.
pragma solidity ^0.8.23;

import {WebAuthn} from "../src/WebAuthn.sol";
import {PasskeyAccount} from "../src/PasskeyAccount.sol";

abstract contract Vectors {
    uint256 constant K0_X = 0x8fd738fb0eab3d57a5dea1a1d93a1ea3d2d506d4cd2e38a39728b81d1773d689;
    uint256 constant K0_Y = 0x7e17252679a3b5afb1f71cb527281d586103a6b73571ea10b8e52b98453af7d2;
    uint256 constant K1_X = 0x1ce98bd56dd84311005a1a9e2097d8797b3fefec6276fe0f31df23771203df3c;
    uint256 constant K1_Y = 0xeb88d2837dfce635c5666de695a4fdfe8bad2ef77476240db30d104ae3db7eb2;

    function _v_small_k0() internal pure returns (WebAuthn.Signature memory) {
        return WebAuthn.Signature({
            authenticatorData: hex"00000000000000000000000000000000000000000000000000000000000000000500000000",
            clientDataJSON: '{"type":"webauthn.get","challenge":"ERERERERERERERERERERERERERERERERERERERERERE","origin":"https://localhost:5173"}',
            challengeIndex: 23,
            typeIndex: 1,
            r: 0x6b7cdb2c95a08c99eccb63e7d32ac631d420b2269b35e5492dae4ac362436de6,
            s: 0x111e141a8225eec168c0e069489fd492460ce03f7a59eb643e4387f919bda7bc
        });
    }

    function _v_small_k1() internal pure returns (WebAuthn.Signature memory) {
        return WebAuthn.Signature({
            authenticatorData: hex"00000000000000000000000000000000000000000000000000000000000000000500000000",
            clientDataJSON: '{"type":"webauthn.get","challenge":"ERERERERERERERERERERERERERERERERERERERERERE","origin":"https://localhost:5173"}',
            challengeIndex: 23,
            typeIndex: 1,
            r: 0xc94ec4a3e164166cb5a30e590dd0b9a23917f3953d71b31367e93dffad1e2614,
            s: 0x7c0029995e2d039d744dd4afb4bf2d76321cf81bc3290eefc0d8ef5636b9396e
        });
    }

    function _v_large_k0() internal pure returns (WebAuthn.Signature memory) {
        return WebAuthn.Signature({
            authenticatorData: hex"00000000000000000000000000000000000000000000000000000000000000000500000000",
            clientDataJSON: '{"type":"webauthn.get","challenge":"IiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiI","origin":"https://localhost:5173"}',
            challengeIndex: 23,
            typeIndex: 1,
            r: 0xf182bc06a3f8a530af8fdd4f62af48663f29fc4828c01415c237477f265d4b3d,
            s: 0x7e34f05ea9c68d4dbafeab7cffb1d481a49ea77d9e7f3e48d27f979d8969617c
        });
    }

    function _v_large_k1() internal pure returns (WebAuthn.Signature memory) {
        return WebAuthn.Signature({
            authenticatorData: hex"00000000000000000000000000000000000000000000000000000000000000000500000000",
            clientDataJSON: '{"type":"webauthn.get","challenge":"IiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiI","origin":"https://localhost:5173"}',
            challengeIndex: 23,
            typeIndex: 1,
            r: 0xfe27c25c0e084a73aced483196a1a5eb9e00abb5279e78623c1235fae964f233,
            s: 0x7705fae8f6a66efcf52892297531e02dfd8d3744deac48adc18a2ec7a20602f2
        });
    }

    function _v_other_k0() internal pure returns (WebAuthn.Signature memory) {
        return WebAuthn.Signature({
            authenticatorData: hex"00000000000000000000000000000000000000000000000000000000000000000500000000",
            clientDataJSON: '{"type":"webauthn.get","challenge":"MzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzM","origin":"https://localhost:5173"}',
            challengeIndex: 23,
            typeIndex: 1,
            r: 0xeacbf73c9f3bd860b7ff9a116f8128dd4beadedbeca99a4ffb79dcbd812595a7,
            s: 0x638b487f52fdb9059edf14f77020873f929be28a71e33d830667fb6daf62bc67
        });
    }

    function _v_other_k1() internal pure returns (WebAuthn.Signature memory) {
        return WebAuthn.Signature({
            authenticatorData: hex"00000000000000000000000000000000000000000000000000000000000000000500000000",
            clientDataJSON: '{"type":"webauthn.get","challenge":"MzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzM","origin":"https://localhost:5173"}',
            challengeIndex: 23,
            typeIndex: 1,
            r: 0xf3068e2ca8413204fbb450d1d7e61bb243c05c24211a565f2fefd02be931222f,
            s: 0x676ca68cc1c749553ef699192f4a61e44e7853107962478fb493f238edffa6ba
        });
    }

    function _v_noUV_k0() internal pure returns (WebAuthn.Signature memory) {
        return WebAuthn.Signature({
            authenticatorData: hex"00000000000000000000000000000000000000000000000000000000000000000100000000",
            clientDataJSON: '{"type":"webauthn.get","challenge":"REREREREREREREREREREREREREREREREREREREREREQ","origin":"https://localhost:5173"}',
            challengeIndex: 23,
            typeIndex: 1,
            r: 0x69f9db4bc9c4777fbf4a18e54ffdd8512623f888746d0c40e7be95a8a7c9f661,
            s: 0x5a37e2e93fc346a0086742752052fb2f9e71605f27b68ed01a1ab023433623ad
        });
    }

    function _v_unknown_k0() internal pure returns (WebAuthn.Signature memory) {
        return WebAuthn.Signature({
            authenticatorData: hex"00000000000000000000000000000000000000000000000000000000000000000500000000",
            clientDataJSON: '{"type":"webauthn.get","challenge":"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVU","origin":"https://localhost:5173"}',
            challengeIndex: 23,
            typeIndex: 1,
            r: 0x6837d52b56cbe8cc363d9829f710e741c2af6768193950057bac1ee31bf7719c,
            s: 0x4ae3efb22417a0ac6dc100a78a227e025803819691b68aa9169081ed7bb5de67
        });
    }

    function _v_erc20_k0() internal pure returns (WebAuthn.Signature memory) {
        return WebAuthn.Signature({
            authenticatorData: hex"00000000000000000000000000000000000000000000000000000000000000000500000000",
            clientDataJSON: '{"type":"webauthn.get","challenge":"ZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmY","origin":"https://localhost:5173"}',
            challengeIndex: 23,
            typeIndex: 1,
            r: 0x28145e0ef350487ed511afb7518670385f7fcdde43a46b573189769b865e54cc,
            s: 0x4b08d14625dbcc83fd991adf2000c418c51cd3ad1940f00836fb649d8c68ef9e
        });
    }

    /// @dev Build a signer array for the constructor.
    function _signers1(uint256 x, uint256 y)
        internal pure returns (PasskeyAccount.PublicKey[] memory a)
    {
        a = new PasskeyAccount.PublicKey[](1);
        a[0] = PasskeyAccount.PublicKey(x, y);
    }

    function _signers2(uint256 x0, uint256 y0, uint256 x1, uint256 y1)
        internal pure returns (PasskeyAccount.PublicKey[] memory a)
    {
        a = new PasskeyAccount.PublicKey[](2);
        a[0] = PasskeyAccount.PublicKey(x0, y0);
        a[1] = PasskeyAccount.PublicKey(x1, y1);
    }
}
